'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gt', {
  listSaves:  ()        => ipcRenderer.invoke('save:list'),
  newCareer:  (slot, p) => ipcRenderer.invoke('career:new', slot, p),
  loadCareer: slot      => ipcRenderer.invoke('career:load', slot),
  deleteSlot: slot      => ipcRenderer.invoke('career:delete', slot),
  state:      ()        => ipcRenderer.invoke('career:state'),
  advance:    ()        => ipcRenderer.invoke('career:advance'),
  closeCareer:()        => ipcRenderer.invoke('career:close'),
  market:     ()        => ipcRenderer.invoke('market:list'),
  buyCar:     (m, l)    => ipcRenderer.invoke('market:buy', m, l),
  carImage:   name      => ipcRenderer.invoke('market:image', name),
  carSpecs:   name      => ipcRenderer.invoke('car:specs', name),
  garage:     ()        => ipcRenderer.invoke('garage:list'),
  office:     ()        => ipcRenderer.invoke('office:list'),
  takeSeat:   id        => ipcRenderer.invoke('office:takeSeat', id),
  formTeam:   (lvl, nm) => ipcRenderer.invoke('office:formTeam', lvl, nm),
  signDriver: (d, e)    => ipcRenderer.invoke('office:sign', d, e),
  myEntries:  ()        => ipcRenderer.invoke('entries:mine'),
  lineup:     ()        => ipcRenderer.invoke('lineup:get'),
  setDriver:  (e, r, d) => ipcRenderer.invoke('lineup:set', e, r, d),
  home:       ()        => ipcRenderer.invoke('home:info'),
  setTutorial:n         => ipcRenderer.invoke('tutorial:set', n),
  raceInfo:   ()        => ipcRenderer.invoke('race:info'),
  racePrepare:leg       => ipcRenderer.invoke('race:prepare', leg),
  writeFiles: files     => ipcRenderer.invoke('race:write', files),
  ams2Path:   ()        => ipcRenderer.invoke('ams2:path'),
  pickAms2:   ()        => ipcRenderer.invoke('ams2:pick'),
  news:       ()        => ipcRenderer.invoke('news:list'),
  markRead:   ()        => ipcRenderer.invoke('news:read'),
  quit:       ()        => ipcRenderer.invoke('app:quit'),
  paths:      ()        => ipcRenderer.invoke('app:paths')
});
